<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>ChoiceScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comment</string>
			<key>match</key>
			<string>.*\*comment.+</string>
			<key>name</key>
			<string>comment.line.cs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>pound key</string>
			<key>match</key>
			<string>#(.|w)+</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>todo</string>
			<key>match</key>
			<string>todo|TODO</string>
			<key>name</key>
			<string>invalid.illegal.cs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variables</string>
			<key>match</key>
			<string>\${.+}</string>
			<key>name</key>
			<string>constant.language.cs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>\*(allow_reuse|choice|create|delete|disable_reuse|else|elseif|elsif|ending|finish|fake_choice|gosub|goto_scene|goto|goto_random_scene|hide_reuse|if|input_text|input_number|image|label|line_break|link|more_games|page_break|print|rand|return|set|share_this_game|star_chart|selectable_if|temp)</string>
			<key>name</key>
			<string>keyword.control.cs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>logic</string>
			<key>match</key>
			<string>!=|=|&gt;|&lt;|&gt;=|&lt;=|%|&amp;</string>
			<key>name</key>
			<string>keyword.operator.cs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers and bools</string>
			<key>match</key>
			<string>[^(a-zA-Z)]\d+|true|false|((\+|-)\d+)</string>
			<key>name</key>
			<string>variable.parameter.cs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>quotation marks</string>
			<key>match</key>
			<string>(")([^"]|"")*(")</string>
			<key>name</key>
			<string>variable.parameter.cs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cs</string>
	<key>uuid</key>
	<string>c4ce72c6-2a40-4270-8d8c-c700517a65a5</string>
</dict>
</plist>