name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ["22.x", "24.x"]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install Packages
              run: npm ci
            - name: Compile
              run: npm run compile --if-present
            - name: Test
              run: npm test

    coverage:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Use Node.js 24.x
              uses: actions/setup-node@v7
              with:
                  node-version: "24.x"
                  cache: "npm"
            - name: Install Packages
              run: npm ci
            - name: Coverage
              run: npm run coverage
            - uses: codecov/codecov-action@v7
              with:
                  files: ./coverage.lcov
                  use_oidc: true
